let blockDataIni=[];
for (let i=3000000;i<3000100;i++){
  let seconds=(Math.floor((Math.random()*10)+1));
  blockDataIni.unshift({num:i,timeLen:seconds});
}
export {blockDataIni};
export const navBackground='transparent';
export const navTogBackground='#2FA3F1';
export const mdBreakpoint=991.98;
export const smBreakpoint=767.98;
export const navContent={
    chinese:[{id:1,
              dropToggle:'开发者',
              dropItem:['Bounty Program','区块链浏览器']
            },{id:2,
              dropToggle:'dApps',
              dropItem:['dApps列表','提交应用']
            },{id:3,
              dropToggle:'信任生态',
              dropItem:['信任锚','节点']
            },{id:4,
              dropToggle:'关于',
              dropItem:['关于我们','联系我们']
            }],
    english:[{id:1,
              dropToggle:'Developer',
              dropItem:['Bounty Program','Explorer']
            },{id:2,
              dropToggle:'dApps',
              dropItem:['dApp List','Submit a App']
            },{id:3,
              dropToggle:'Trust Ecosystem',
              dropItem:['Trust Anchor','Node']
            },{id:4,
              dropToggle:'About',
              dropItem:['About us','Contact us']
            }]
    };
export const dAppdata = [{
      id:"1",
      name:{
        appName:"HyperSnakes",
        appURL:"https://explorer.ont.io/contract/all/4765d8fa1c3f8f938ddb19ac5e848b422f67bfa9/10/1",
        des:"HyperSnakes is the first game where blockchain meets global real-time multiplayer battle game.",
        category:"Game",
        image:require("./images/DappList/app1.png")
      },
      activeUser:{
        hours:"3,613",
        days:"26,485"
      },
      volume:{
        hours:"3,651",
        days:"26,575"
      },
      transactions:{
        hours:"6,039.27",
        days:"28,176.93"
      },
      weeklyReward:0,
      totalReward:0
    },{
      id:"2",
      name:{
        appName:"HyperDragons Go!",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app1.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'4,728',
      totalReward:'54,717.32'
    },{
      id:"3",
      name:{
        appName:"区块战争",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app2.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"4",
      name:{
        appName:"Spokkz",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app3.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"5",
      name:{
        appName:"贪吃蛇",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app4.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'3760',
      totalReward:'3760'
    },{
      id:"6",
      name:{
        appName:"ONS",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Others",
        image:require("./images/DappList/app5.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"7",
      name:{
        appName:"加密西游",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app6.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"8",
      name:{
        appName:"大鸟撞小鸟",
        appURL:"https://explorer.ont.io/contract/e1e9a4fe5d9bd4adef0a1e58fa05961526466487/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app7.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"9",
      name:{
        appName:"抢手总动员",
        appURL:"https://explorer.ont.io/contract/e1e9a4fe5d9bd4adef0a1e58fa05961526466487/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app8.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'4,051',
      totalReward:'11,369.85'
    },{
      id:"10",
      name:{
        appName:"ONTLAND",
        appURL:"https://explorer.ont.io/contract/e1e9a4fe5d9bd4adef0a1e58fa05961526466487/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app9.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"11",
      name:{
        appName:"熊本冲",
        appURL:"https://explorer.ont.io/contract/all/4765d8fa1c3f8f938ddb19ac5e848b422f67bfa9/10/1",
        des:"HyperSnakes is the first game where blockchain meets global real-time multiplayer battle game.",
        category:"Game",
        image:require("./images/DappList/app11.png")
      },
      activeUser:{
        hours:"3,613",
        days:"26,485"
      },
      volume:{
        hours:"3,651",
        days:"26,575"
      },
      transactions:{
        hours:"6,039.27",
        days:"28,176.93"
      },
      weeklyReward:'2,893',
      totalReward:'4,138.67'
    },{
      id:"12",
      name:{
        appName:"爆爽弹一弹",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app12.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'9,593.35'
    },{
      id:"13",
      name:{
        appName:"区块忍者",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app13.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"14",
      name:{
        appName:"出逃吧！鸭梨君",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app14.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"15",
      name:{
        appName:"超级星球",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app15.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'3760',
      totalReward:'3760'
    },{
      id:"16",
      name:{
        appName:"像素鸟",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Others",
        image:require("./images/DappList/app16.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'13,670.76'
    },{
      id:"17",
      name:{
        appName:"本体传奇",
        appURL:"https://explorer.ont.io/contract/all/cae215265a5e348bfd603b8db22893aa74b42417/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app17.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"18",
      name:{
        appName:"Pet2048",
        appURL:"https://explorer.ont.io/contract/e1e9a4fe5d9bd4adef0a1e58fa05961526466487/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app18.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    },{
      id:"19",
      name:{
        appName:"本体传奇",
        appURL:"https://explorer.ont.io/contract/e1e9a4fe5d9bd4adef0a1e58fa05961526466487/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app19.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'1,647'
    },{
      id:"20",
      name:{
        appName:"极限弯道",
        appURL:"https://explorer.ont.io/contract/e1e9a4fe5d9bd4adef0a1e58fa05961526466487/10/1",
        des:"The renowned Idle RPG game is starting an amazing blockchain game journey with you.",
        category:"Game",
        image:require("./images/DappList/app20.png")
      },
      activeUser:{
        hours:"4,638",
        days:"29,098"
      },
      volume:{
        hours:"5,647",
        days:"35,560"
      },
      transactions:{
        hours:"2,548.9",
        days:"15,805.53"
      },
      weeklyReward:'0',
      totalReward:'0'
    }];